resolver: lts-13.26

packages:
- .

extra-deps:
- git: https://github.com/purescript/purescript
  commit: 4dd32c48a372bb8a5250140d19af8aa18a6358d7
- happy-1.19.9
- language-javascript-0.7.0.0
- network-3.0.1.1
- these-1.0.1
- semialign-1

nix:
  shell-file: stack.nix

flags:
  aeson-pretty:
    lib-only: true
  these:
    assoc: false
    quickcheck: false
